<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>org.dromara</groupId>
		<artifactId>unimed-cloud-plus</artifactId>
		<version>${revision}</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>unimed-gateway-mvc</artifactId>

	<description>
		unimed-gateway-mvc网关模块
	</description>

	<dependencies>

		<!-- SpringCloud Gateway -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway-server-webmvc</artifactId>
		</dependency>

		<!-- SpringBoot Web容器 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-boot-starter-tomcat</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- web 容器使用 undertow 性能更强 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-loadbalancer</artifactId>
		</dependency>

		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
		</dependency>

		<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>unimed-common-nacos</artifactId>
		</dependency>

		<!-- SpringBoot Actuator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-http</artifactId>
		</dependency>

		<!-- Sa-Token 权限认证 -->
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-spring-boot3-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>unimed-common-satoken</artifactId>
		</dependency>

		<!-- Unimed Common Redis-->
		<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>unimed-common-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>unimed-common-tenant</artifactId>
		</dependency>

		<!-- 自定义负载均衡(多团队开发使用) -->
		<!-- <dependency>-->
		<!-- <groupId>org.dromara</groupId>-->
		<!-- <artifactId>unimed-common-loadbalancer</artifactId>-->
		<!-- </dependency>-->

		<!-- ELK 日志收集 -->
		<!-- <dependency>-->
		<!-- <groupId>org.dromara</groupId>-->
		<!-- <artifactId>unimed-common-logstash</artifactId>-->
		<!-- </dependency>-->

		<!-- skywalking 日志收集 -->
		<!-- <dependency>-->
		<!-- <groupId>org.dromara</groupId>-->
		<!-- <artifactId>unimed-common-skylog</artifactId>-->
		<!-- </dependency>-->

		<!-- prometheus 监控 -->
		<!-- <dependency>-->
		<!-- <groupId>org.dromara</groupId>-->
		<!-- <artifactId>unimed-common-prometheus</artifactId>-->
		<!-- </dependency>-->

	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
