-- ----------------------------
-- 慢病医疗文档 OCR 数据录入
-- ----------------------------

CREATE TABLE IF NOT EXISTS `ch_medical_document_ocr_task` (
  `task_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'OCR任务ID',
  `patient_id` BIGINT DEFAULT NULL COMMENT '患者ID，建档前可为空',
  `source_type` VARCHAR(20) NOT NULL COMMENT '来源(ADMIN/DOCTOR/PATIENT)',
  `document_type` VARCHAR(30) NOT NULL COMMENT '文档类型(MEDICAL_RECORD_HOME/DISCHARGE_SUMMARY/LAB_REPORT/EXAM_REPORT/DIAGNOSIS_REPORT/OTHER)',
  `input_type` VARCHAR(20) NOT NULL COMMENT '输入类型(IMAGE_BASE64/IMAGE_URL/PDF_FILE/OSS_FILE)',
  `oss_id` BIGINT DEFAULT NULL COMMENT '资源文件ID',
  `file_url` VARCHAR(500) DEFAULT NULL COMMENT '文件访问地址',
  `file_md5` VARCHAR(64) DEFAULT NULL COMMENT '文件MD5',
  `status` VARCHAR(20) NOT NULL COMMENT '状态(PENDING/RECOGNIZING/SUCCESS/FAILED/CONFIRMED/DISCARDED)',
  `report_draft_json` JSON DEFAULT NULL COMMENT '报告主信息草稿JSON',
  `raw_ocr_json` JSON DEFAULT NULL COMMENT '原始OCR JSON',
  `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  `error_msg` VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
  `confirmed_patient_id` BIGINT DEFAULT NULL COMMENT '确认后的患者ID',
  `confirmed_metric_count` INT DEFAULT 0 COMMENT '确认入库指标数量',
  `confirmed_exam_id` BIGINT DEFAULT NULL COMMENT '确认后的检查检验报告ID',
  `confirmed_by` BIGINT DEFAULT NULL COMMENT '确认人',
  `confirmed_time` DATETIME DEFAULT NULL COMMENT '确认时间',
  `create_dept` BIGINT DEFAULT NULL COMMENT '创建部门',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`task_id`),
  KEY `idx_mdot_patient` (`patient_id`),
  KEY `idx_mdot_status_time` (`status`, `create_time`),
  KEY `idx_mdot_file` (`patient_id`, `file_md5`),
  KEY `idx_mdot_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢病医疗文档OCR任务表';

CREATE TABLE IF NOT EXISTS `ch_medical_document_ocr_archive_draft` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT NOT NULL COMMENT 'OCR任务ID',
  `matched_patient_id` BIGINT DEFAULT NULL COMMENT '身份证命中的已有患者ID',
  `action_type` VARCHAR(20) DEFAULT NULL COMMENT '建议动作(CREATE_ARCHIVE/UPDATE_ARCHIVE)',
  `profile_draft_json` JSON DEFAULT NULL COMMENT '患者主档草稿JSON',
  `disease_draft_json` JSON DEFAULT NULL COMMENT '患者病种草稿JSON',
  `unmapped_field_json` JSON DEFAULT NULL COMMENT '未映射字段JSON',
  `need_confirm` TINYINT(1) DEFAULT 1 COMMENT '是否待人工确认',
  `confirmed_patient_id` BIGINT DEFAULT NULL COMMENT '确认后的患者ID',
  `raw_item_json` JSON DEFAULT NULL COMMENT '原始建档相关JSON',
  `create_dept` BIGINT DEFAULT NULL COMMENT '创建部门',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`id`),
  KEY `idx_mdoad_task` (`task_id`),
  KEY `idx_mdoad_patient` (`matched_patient_id`),
  KEY `idx_mdoad_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢病医疗文档OCR建档草稿表';

CREATE TABLE IF NOT EXISTS `ch_medical_document_ocr_metric_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT NOT NULL COMMENT 'OCR任务ID',
  `original_name` VARCHAR(100) DEFAULT NULL COMMENT 'OCR原始项目名称',
  `metric_type` VARCHAR(30) DEFAULT NULL COMMENT '映射后的慢病指标类型',
  `metric_value` VARCHAR(500) DEFAULT NULL COMMENT '指标值',
  `unit` VARCHAR(50) DEFAULT NULL COMMENT '单位',
  `reference_value_min` DECIMAL(10,2) DEFAULT NULL COMMENT '参考下限',
  `reference_value_max` DECIMAL(10,2) DEFAULT NULL COMMENT '参考上限',
  `reference_range` VARCHAR(100) DEFAULT NULL COMMENT '原始参考范围',
  `is_abnormal` TINYINT(1) DEFAULT 0 COMMENT '是否异常',
  `confidence` DECIMAL(6,4) DEFAULT NULL COMMENT '识别置信度',
  `need_confirm` TINYINT(1) DEFAULT 0 COMMENT '是否待人工确认',
  `confirmed_metric_id` BIGINT DEFAULT NULL COMMENT '确认后的指标ID',
  `raw_item_json` JSON DEFAULT NULL COMMENT '原始项目JSON',
  `create_dept` BIGINT DEFAULT NULL COMMENT '创建部门',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`id`),
  KEY `idx_mdomi_task` (`task_id`),
  KEY `idx_mdomi_metric` (`metric_type`),
  KEY `idx_mdomi_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢病医疗文档OCR指标草稿表';

CREATE TABLE IF NOT EXISTS `ch_medical_document_ocr_report_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT NOT NULL COMMENT 'OCR任务ID',
  `item_name` VARCHAR(100) DEFAULT NULL COMMENT '检查检验项目名称',
  `item_code` VARCHAR(50) DEFAULT NULL COMMENT '项目编码',
  `result_value` VARCHAR(500) DEFAULT NULL COMMENT '结果/结论',
  `unit` VARCHAR(50) DEFAULT NULL COMMENT '单位',
  `reference_range` VARCHAR(100) DEFAULT NULL COMMENT '参考范围',
  `is_abnormal` TINYINT(1) DEFAULT 0 COMMENT '是否异常',
  `confidence` DECIMAL(6,4) DEFAULT NULL COMMENT '识别置信度',
  `need_confirm` TINYINT(1) DEFAULT 0 COMMENT '是否待人工确认',
  `confirmed_exam_item_id` BIGINT DEFAULT NULL COMMENT '确认后的报告项目ID',
  `raw_item_json` JSON DEFAULT NULL COMMENT '原始项目JSON',
  `create_dept` BIGINT DEFAULT NULL COMMENT '创建部门',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`id`),
  KEY `idx_mdori_task` (`task_id`),
  KEY `idx_mdori_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢病医疗文档OCR报告项目草稿表';
