-- 慢病模块补建缺失表（线上库比 unimed-chronic.sql 少 10 张表）
-- 生成依据：information_schema 对比 script/sql/unimed-chronic.sql
-- 幂等：全部使用 CREATE TABLE IF NOT EXISTS

CREATE TABLE IF NOT EXISTS `ch_lab_test`  (
  `test_id` bigint NOT NULL AUTO_INCREMENT COMMENT '检验ID',
  `patient_id` bigint NULL DEFAULT NULL COMMENT '患者ID',
  `test_date` datetime NULL DEFAULT NULL COMMENT '检验日期',
  `test_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检验类型(血常规/肝功能/肾功能等)',
  `test_items` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '检验项目明细JSON',
  `report_image` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '报告图片URL',
  `hospital` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检验医院',
  `doctor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检验医生',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`test_id`) USING BTREE,
  INDEX `idx_lt_patient_id`(`patient_id` ASC) USING BTREE,
  INDEX `idx_lt_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '检验记录表' ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `ch_medical_exam`  (
  `exam_id` bigint NOT NULL AUTO_INCREMENT COMMENT '检查ID',
  `patient_id` bigint NULL DEFAULT NULL COMMENT '患者ID',
  `exam_date` datetime NULL DEFAULT NULL COMMENT '检查日期',
  `exam_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查类型(X光/CT/B超/心电图等)',
  `exam_part` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查部位',
  `exam_result` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '检查结果描述',
  `exam_conclusion` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查结论',
  `report_image` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '报告图片URL',
  `hospital` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查医院',
  `doctor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查医生',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`exam_id`) USING BTREE,
  INDEX `idx_me_patient_id`(`patient_id` ASC) USING BTREE,
  INDEX `idx_me_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '检查记录表' ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `ch_ocr_draft`  (
  `draft_id` bigint NOT NULL AUTO_INCREMENT COMMENT '草稿ID',
  `task_id` bigint NULL DEFAULT NULL COMMENT 'OCR任务ID',
  `draft_category` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '草稿类型(PROFILE/DISEASE/METRIC/REPORT)',
  `draft_data` json NULL COMMENT '识别结构化数据',
  `confidence` decimal(5, 2) NULL DEFAULT NULL COMMENT '识别置信度(0-100)',
  `need_confirm` tinyint(1) NULL DEFAULT 1 COMMENT '是否待人工确认',
  `confirm_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '确认状态(PENDING/CONFIRMED/DISCARDED)',
  `written_biz_id` bigint NULL DEFAULT NULL COMMENT '入库后的业务ID',
  `matched_patient_id` bigint NULL DEFAULT NULL COMMENT '身份证命中的已有患者ID',
  `action_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '建议动作(CREATE_ARCHIVE/UPDATE_ARCHIVE)',
  `unmapped_field_json` json NULL COMMENT '未映射字段JSON',
  `metric_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '映射后的慢病指标类型',
  `original_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'OCR原始项目名称',
  `metric_value` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '指标值(METRIC类)',
  `unit` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '单位',
  `reference_value_min` decimal(10, 2) NULL DEFAULT NULL COMMENT '参考下限',
  `reference_value_max` decimal(10, 2) NULL DEFAULT NULL COMMENT '参考上限',
  `reference_range` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '原始参考范围',
  `is_abnormal` tinyint(1) NULL DEFAULT 0 COMMENT '是否异常',
  `item_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查检验项目名称(REPORT类)',
  `item_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '项目编码(REPORT类)',
  `result_value` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '结果/结论(REPORT类)',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`draft_id`) USING BTREE,
  INDEX `idx_od_task_id`(`task_id` ASC) USING BTREE,
  INDEX `idx_od_confirm_status`(`confirm_status` ASC) USING BTREE,
  INDEX `idx_od_tenant_id`(`tenant_id` ASC) USING BTREE,
  INDEX `idx_od_category_task`(`draft_category` ASC, `task_id` ASC) USING BTREE,
  INDEX `idx_od_metric_type`(`metric_type` ASC) USING BTREE,
  INDEX `idx_od_matched_patient`(`matched_patient_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'OCR草稿表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_ocr_task`  (
  `task_id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `patient_id` bigint NULL DEFAULT NULL COMMENT '目标患者ID',
  `doc_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '文档类型(LAB_REPORT/EXAM_REPORT/MEDICAL_RECORD_HOME/DISCHARGE_SUMMARY/DIAGNOSIS_REPORT)',
  `input_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '输入形式(IMAGE_BASE64/IMAGE_URL/OSS_FILE/PDF_FILE)',
  `file_id` bigint NULL DEFAULT NULL COMMENT '源文件ID',
  `oss_id` bigint NULL DEFAULT NULL COMMENT 'OSS 资源ID(历史兼容，与 file_id 二选一)',
  `file_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '文件访问地址(历史兼容)',
  `file_md5` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '文件MD5(用于幂等判重)',
  `source_terminal` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发起端(ADMIN/DOCTOR/PATIENT)',
  `task_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '任务状态(PENDING/PROCESSING/SUCCESS/FAILED/CONFIRMED/DISCARDED)',
  `recognized_at` datetime NULL DEFAULT NULL COMMENT '识别完成时间',
  `confirmed_at` datetime NULL DEFAULT NULL COMMENT '确认入库时间',
  `confirmer_user_id` bigint NULL DEFAULT NULL COMMENT '确认人用户ID',
  `report_draft_json` json NULL COMMENT '报告主信息草稿JSON(历史兼容)',
  `raw_ocr_json` json NULL COMMENT '原始OCR JSON(调试/复盘用)',
  `error_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '错误码(失败时填写)',
  `error_msg` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '错误信息(失败时填写)',
  `confirmed_patient_id` bigint NULL DEFAULT NULL COMMENT '确认后的患者ID',
  `confirmed_metric_count` int NULL DEFAULT 0 COMMENT '确认入库指标数量',
  `confirmed_exam_id` bigint NULL DEFAULT NULL COMMENT '确认后的检查检验报告ID',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`task_id`) USING BTREE,
  INDEX `idx_ot_patient_id`(`patient_id` ASC) USING BTREE,
  INDEX `idx_ot_task_status`(`task_status` ASC) USING BTREE,
  INDEX `idx_ot_tenant_id`(`tenant_id` ASC) USING BTREE,
  INDEX `idx_ot_file_md5`(`patient_id` ASC, `file_md5` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'OCR任务表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_ops_health_check`  (
  `check_id` bigint NOT NULL AUTO_INCREMENT COMMENT '巡检ID',
  `check_batch` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '巡检批次号',
  `target_component` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '目标组件(DB/REDIS/NACOS/MQ/HIS/LIS/PACS 等)',
  `check_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '检查结果(SUCCESS/FAILED/TIMEOUT)',
  `response_ms` bigint NULL DEFAULT NULL COMMENT '响应时长(毫秒)',
  `error_msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '错误信息(失败时填写)',
  `alert_triggered` tinyint(1) NULL DEFAULT 0 COMMENT '是否触发告警',
  `check_time` datetime NULL DEFAULT NULL COMMENT '巡检时间',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`check_id`) USING BTREE,
  INDEX `idx_ohc_check_batch`(`check_batch` ASC) USING BTREE,
  INDEX `idx_ohc_check_time`(`check_time` ASC) USING BTREE,
  INDEX `idx_ohc_component`(`target_component` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '运维健康巡检表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_ops_rerun_ticket`  (
  `ticket_id` bigint NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  `task_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重跑任务编码',
  `apply_user_id` bigint NULL DEFAULT NULL COMMENT '申请人用户ID',
  `apply_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '申请理由',
  `audit_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '审批状态(PENDING/APPROVED/REJECTED)',
  `auditor_user_id` bigint NULL DEFAULT NULL COMMENT '审批人用户ID',
  `audit_time` datetime NULL DEFAULT NULL COMMENT '审批时间',
  `audit_remark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '审批备注',
  `exec_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '执行状态(NOT_STARTED/RUNNING/SUCCESS/FAILED)',
  `exec_start_time` datetime NULL DEFAULT NULL COMMENT '执行开始时间',
  `exec_end_time` datetime NULL DEFAULT NULL COMMENT '执行结束时间',
  `exec_result` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '执行结果摘要',
  `affected_range` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '影响数据范围',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`ticket_id`) USING BTREE,
  INDEX `idx_ort_task_code`(`task_code` ASC) USING BTREE,
  INDEX `idx_ort_audit_status`(`audit_status` ASC) USING BTREE,
  INDEX `idx_ort_exec_status`(`exec_status` ASC) USING BTREE,
  INDEX `idx_ort_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '运维任务重跑工单表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_patient_close_apply`  (
  `apply_id` bigint NOT NULL AUTO_INCREMENT COMMENT '结案申请ID',
  `patient_id` bigint NULL DEFAULT NULL COMMENT '患者ID',
  `close_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '结案类型(VOLUNTARY/TRANSFER/LOST/DEATH)',
  `apply_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '申请理由',
  `evidence_file_id` bigint NULL DEFAULT NULL COMMENT '证据附件文件ID',
  `snapshot_json` json NULL COMMENT '审核通过后用于追溯的快照',
  `applicant_user_id` bigint NULL DEFAULT NULL COMMENT '申请人用户ID',
  `apply_source` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '申请发起端(ADMIN/DOCTOR/PATIENT)',
  `audit_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '审核状态(PENDING/APPROVED/REJECTED/WITHDRAWN)',
  `auditor_user_id` bigint NULL DEFAULT NULL COMMENT '审核人用户ID',
  `audit_time` datetime NULL DEFAULT NULL COMMENT '审核时间',
  `audit_remark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '审核备注',
  `reject_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '驳回理由(仅驳回时填写)',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`apply_id`) USING BTREE,
  INDEX `idx_pca_patient_id`(`patient_id` ASC) USING BTREE,
  INDEX `idx_pca_audit_status`(`audit_status` ASC) USING BTREE,
  INDEX `idx_pca_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '患者结案申请表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_patient_tag_dict`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tag_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '标签编码（业务唯一）如 RISK_HIGH / TAG0001',
  `tag_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '标签名称 如 高危',
  `tag_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '标签大类（字典 chronic_tag_type）RISK/CUSTOM/COMORBIDITY',
  `category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '细分类（行为/社会/经济/风险等，可自由扩展）',
  `color` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '前端展示色 如 #FF4D4F',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0' COMMENT '状态 0启用 1停用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '租户ID（NULL 表示全局系统预置）',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志（0存在 2删除）',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tag_code_tenant`(`tag_code` ASC, `tenant_id` ASC) USING BTREE,
  INDEX `idx_tag_type`(`tag_type` ASC) USING BTREE,
  INDEX `idx_status_sort`(`status` ASC, `sort_order` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '慢病-患者标签字典' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_sos_record`  (
  `sos_id` bigint NOT NULL AUTO_INCREMENT COMMENT '求助ID',
  `patient_id` bigint NULL DEFAULT NULL COMMENT '患者ID',
  `gps_lng` decimal(10, 6) NULL DEFAULT NULL COMMENT 'GPS经度',
  `gps_lat` decimal(10, 6) NULL DEFAULT NULL COMMENT 'GPS纬度',
  `gps_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '反向地理编码地址',
  `notify_doctor_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '通知医生状态(PENDING/SENT/FAILED)',
  `notify_emergency_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '通知紧急联系人状态(PENDING/SENT/FAILED)',
  `notify_channel_summary` json NULL COMMENT '通知渠道明细',
  `event_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '事件状态(NEW/HANDLING/RESOLVED/FALSE_ALARM)',
  `handler_user_id` bigint NULL DEFAULT NULL COMMENT '处置人用户ID',
  `handle_time` datetime NULL DEFAULT NULL COMMENT '处置时间',
  `handle_remark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '处置备注',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`sos_id`) USING BTREE,
  INDEX `idx_sos_patient_id`(`patient_id` ASC) USING BTREE,
  INDEX `idx_sos_event_status`(`event_status` ASC) USING BTREE,
  INDEX `idx_sos_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '紧急求助记录表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ch_webhook_subscription`  (
  `sub_id` bigint NOT NULL AUTO_INCREMENT COMMENT '订阅ID',
  `third_party_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '第三方系统名称',
  `event_types` json NULL COMMENT '订阅事件列表(如[WARNING_CREATED, FOLLOWUP_DONE])',
  `callback_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '回调地址',
  `signature_secret` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '签名密钥(HMAC 签名校验)',
  `retry_max` int NULL DEFAULT 5 COMMENT '最大重试次数',
  `retry_strategy` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重试策略(EXPONENTIAL_BACKOFF/LINEAR)',
  `is_active` tinyint(1) NULL DEFAULT 1 COMMENT '是否启用',
  `last_invoke_time` datetime NULL DEFAULT NULL COMMENT '最近推送时间',
  `last_invoke_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '最近推送状态',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `create_by` bigint NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
  PRIMARY KEY (`sub_id`) USING BTREE,
  INDEX `idx_ws_is_active`(`is_active` ASC) USING BTREE,
  INDEX `idx_ws_tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'Webhook订阅表' ROW_FORMAT = Dynamic;
